spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
    data: data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      path: /h2
      enabled: true


logging:
  level:
    org:
      hibernate:
        SQL: INFO